### ISSUE TITLE
Llama 2 image builds on Python 3.8 while `inference_api.py` uses Python 3.9 features

### ISSUE THREAD

**Issue by surajssd** [kaito-project/kaito#797]
**Describe the bug**

Llama 2 image builds on Python 3.8 while `inference_api.py` uses Python 3.9 features. This causes the following error when running the image:

```bash
[2024-12-27 15:23:35,335] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2024-12-27 15:23:35,335] torch.distributed.run: [WARNING]
[2024-12-27 15:23:35,335] torch.distributed.run: [WARNING] *****************************************
[2024-12-27 15:23:35,335] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your sys
tem being overloaded, please further tune the variable for optimal performance in your application as needed.
[2024-12-27 15:23:35,335] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "inference_api.py", line 10, in <module>
    from typing import Annotated, Any, Dict, List, Optional, Union
ImportError: cannot import name 'Annotated' from 'typing' (/usr/local/lib/python3.8/typing.py)
...
```

**Steps To Reproduce**

Build the llama2 image using the following commands:

```bash
export MODEL_ID="meta-llama/llama-2-70b"
git clone git@hf.co:$MODEL_ID

export VERSION="1cb3547"
export IMAGE_NAME="registry/${MODEL_ID}:${VERSION}"
export WEIGHTS_PATH="$(basename ${MODEL_ID})"

docker build \
    -t "${IMAGE_NAME}" \
    --file kaito/docker/presets/models/llama-2/Dockerfile \
    --build-arg WEIGHTS_PATH=${WEIGHTS_PATH} \
    --build-arg MODEL_TYPE=llama2-completion \
    --build-arg VERSION=${VERSION} \
    --push \
    ./
```

When you run the above image it fails to start with the error mentioned above.

**Expected behavior**

Update the dockerfile to use Python 3.9 instead of Python 3.8: https://github.com/kaito-project/kaito/blob/c96b10ea0d94d660aa18423966453696cbd2517e/docker/presets/models/llama-2/Dockerfile#L7
