### PR TITLE
Fix fine-tuning script for transformers 4.49.0

### LINKED ISSUE #928: Fine-tuning script was broken when upgrade transformers to 4.49
**Describe the bug**

```
vllm==0.7.2
transformers == 4.49.0
torch==2.5.1
```

We bump the dep version when upgrading vllm to 0.7.2. However, there are some breaking change in transformers library and fine-tuning script is broken. 

We should evaluate the behavior of the new version and fix it.

**Steps To Reproduce**

**Expected behavior**

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Install tools:
- Others:

**Additional context**

### PR DESCRIPTION
**Pull request by meghana-0211**
Fixes #928

This PR fixes the fine-tuning script to work with transformers 4.49.0. The main changes are:

1. Properly setting the `dataset_text_field` in the DatasetManager class
2. Ensuring compatibility with the updated SFTTrainer API

Tested with:
- transformers 4.49.0
- vllm 0.7.2
- torch 2.5.1

### CODE REVIEW

**Comment by zhuangqh** [comment]
Thank you for your investigation.
```
Traceback (most recent call last):
  File "/workspace/tfs/fine_tuning.py", line 27, in <module>
    parsed_configs = parse_configs(CONFIG_YAML)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tfs/parser.py", line 67, in parse_configs
    yaml_parsed_instance = parse_section(section_name, training_config.get(section_name, {}))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tfs/parser.py", line 53, in parse_section
    return parser.parse_args_into_dataclasses(cli_args)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/transformers/hf_argparser.py", line 357, in parse_args_into_dataclasses
    obj = dtype(**inputs)
          ^^^^^^^^^^^^^^^
  File "<string>", line 11, in __init__
  File "/usr/local/lib/python3.12/site-packages/transformers/data/data_collator.py", line 832, in __post_init__
    if self.mlm and self.tokenizer.mask_token is None:
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'PreTrainedTokenizer' has no attribute 'mask_token'. Did you mean: '_add_tokens'?
```

I can still get this error after applying your change.

**Comment by zhuangqh** [comment]
close via #940
